name: sncrs_prod

services:
  web:
    env_file:
      - config/.env.prod
    build:
      context: sncrs
      dockerfile: Containerfile
    restart: always
    ports:
      - "${ACCESS_PORT}:8020"
    volumes:
      - static_volume:/sncrs/static
      - media_volume:/sncrs/media
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - config/.env.prod

volumes:
  static_volume:
  media_volume:
  postgres_data: