# Generated by Django 3.2.3 on 2021-05-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmashNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('friend_code', models.CharField(max_length=20, null=True)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('bracket_demon', models.ManyToManyField(related_name='_data_person_bracket_demon_+', to='data.Person')),
                ('mains', models.ManyToManyField(to='data.Character')),
                ('rivals', models.ManyToManyField(related_name='_data_person_rivals_+', to='data.Person')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_score', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('p2_score', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('p1_wins', models.IntegerField(null=True)),
                ('p2_wins', models.IntegerField(null=True)),
                ('p1_score_change', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('p2_score_change', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('match_url', models.URLField(null=True)),
                ('p1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_match_set', to='data.person')),
                ('p2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_match_set', to='data.person')),
                ('sn_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.smashnight')),
            ],
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(null=True)),
                ('sn_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.smashnight')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seed', models.IntegerField(null=True)),
                ('end_seed', models.IntegerField(null=True)),
                ('start_score', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('end_score', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('end_bracket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_attendee_set', to='data.bracket')),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.person')),
                ('sn_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.smashnight')),
                ('start_bracket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_attendee_set', to='data.bracket')),
            ],
        ),
    ]
