# Generated by Django 3.2.3 on 2021-05-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tag',
            field=models.CharField(default='TSM', max_length=10),
            preserve_default=False,
        ),
    ]
