# Generated by Django 3.2.3 on 2021-05-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210520_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='end_bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_attendee_set', to='data.bracket'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='end_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='end_seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='start_bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_attendee_set', to='data.bracket'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='start_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='start_seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1_match_set', to='data.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_score_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2_match_set', to='data.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_score_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='sn_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.smashnight'),
        ),
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='aliases',
            field=models.ManyToManyField(blank=True, to='data.Alias'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bracket_demon',
            field=models.ManyToManyField(blank=True, null=True, related_name='_data_person_bracket_demon_+', to='data.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='friend_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mains',
            field=models.ManyToManyField(blank=True, null=True, to='data.Character'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='rivals',
            field=models.ManyToManyField(blank=True, null=True, related_name='_data_person_rivals_+', to='data.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.team'),
        ),
    ]
