# Generated by Django 3.2.3 on 2021-05-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210520_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='p1_id',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='p2_id',
            new_name='p2',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='sn_id',
            new_name='sn',
        ),
    ]
