# Generated by Django 3.2.3 on 2021-05-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210520_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracket',
            old_name='sn_id',
            new_name='sn',
        ),
    ]
