# Generated by Django 3.2.3 on 2021-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_sn_id_bracket_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='team',
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ManyToManyField(blank=True, to='data.Team'),
        ),
    ]
