# Generated by Django 3.2.3 on 2021-05-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210520_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='team',
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.team'),
        ),
    ]
