# Generated by Django 3.2.3 on 2021-05-20 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210520_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.person')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.person')),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='placements',
            field=models.ManyToManyField(blank=True, to='data.Placement'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='seeds',
            field=models.ManyToManyField(blank=True, to='data.Seed'),
        ),
    ]
