# Generated by Django 3.2.3 on 2021-05-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20210520_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='aliases',
        ),
        migrations.AddField(
            model_name='alias',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.person'),
        ),
    ]
