# Generated by Django 3.2.3 on 2021-05-20 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20210520_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.person'),
            preserve_default=False,
        ),
    ]
