# Generated by Django 3.2.3 on 2021-05-20 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_alias_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracket',
            name='placements',
        ),
        migrations.RemoveField(
            model_name='bracket',
            name='seeds',
        ),
        migrations.AddField(
            model_name='placement',
            name='bracket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.bracket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seed',
            name='bracket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.bracket'),
            preserve_default=False,
        ),
    ]
