# Generated by Django 3.2.3 on 2021-05-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_person_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Bracket Match'), (1, 'Challenge Match'), (2, 'Crew Battle'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tag',
            field=models.IntegerField(blank=True, choices=[(0, 'Member'), (1, 'Guest'), (2, 'Other')], null=True),
        ),
    ]
