# Generated by Django 3.2.3 on 2021-05-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20210522_0604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['display_name'], 'verbose_name_plural': 'people'},
        ),
        migrations.AddField(
            model_name='team',
            name='team_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
