# Generated by Django 3.2.3 on 2021-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_stage_stagetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['character_id', 'name']},
        ),
        migrations.AddField(
            model_name='character',
            name='character_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
