# Generated by Django 3.2.3 on 2021-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20210525_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'ordering': ['lower_bound'],
            },
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['name']},
        ),
    ]
