# Generated by Django 3.2.3 on 2021-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_alter_smashnight_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='smashnight',
            name='night_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
