# Generated by Django 3.2.3 on 2021-05-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_smashnight_night_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smashnight',
            options={'ordering': ['-date'], 'verbose_name_plural': 'smashnights'},
        ),
    ]
