# Generated by Django 3.2.3 on 2021-05-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_smashnight_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_rank', models.IntegerField(blank=True, null=True)),
                ('end_rank', models.IntegerField(blank=True, null=True)),
                ('start_score', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('end_score', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.person')),
                ('sn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.smashnight')),
            ],
        ),
    ]
