# Generated by Django 3.2.3 on 2021-05-27 16:40

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_personsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': [django.db.models.functions.text.Lower('display_name')], 'verbose_name_plural': 'people'},
        ),
    ]
