# Generated by Django 3.2.3 on 2021-05-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personsnapshot',
            options={'ordering': ['sn', 'person']},
        ),
    ]
