# Generated by Django 3.2.3 on 2021-05-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20210527_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonSnapshot',
        ),
    ]
