# Generated by Django 3.2.3 on 2021-05-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_alter_personsnapshot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personsnapshot',
            options={'ordering': ['sn__date', 'person__team', 'person__display_name']},
        ),
    ]
