# Generated by Django 3.2.3 on 2021-05-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20210527_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ['bracket', 'place']},
        ),
        migrations.AlterModelOptions(
            name='seed',
            options={'ordering': ['bracket', 'seed']},
        ),
    ]
