# Generated by Django 3.2.3 on 2021-05-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_auto_20210528_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tag',
            field=models.IntegerField(blank=True, choices=[(0, 'Member'), (1, 'Guest'), (2, 'Retired'), (3, 'Other')], null=True),
        ),
    ]
