# Generated by Django 3.2.3 on 2021-05-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_match_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px_wins', models.IntegerField(blank=True, null=True)),
                ('py_wins', models.IntegerField(blank=True, null=True)),
                ('px_additional_wins', models.IntegerField(blank=True, null=True)),
                ('py_additional_wins', models.IntegerField(blank=True, null=True)),
                ('matchup_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.matchuptype')),
                ('px', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='px_matchup_set', to='data.person')),
                ('py', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='py_matchup_set', to='data.person')),
            ],
        ),
    ]
