# Generated by Django 3.2.3 on 2021-05-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_matchup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchup',
            options={'ordering': ['py__display_name']},
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='end_bracket',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='start_bracket',
        ),
    ]
