# Generated by Django 3.2.3 on 2021-05-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20210530_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='px_additional_wins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='py_additional_wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
