# Generated by Django 3.2.3 on 2021-05-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20210530_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='smashnight',
            name='automations_ran',
            field=models.BooleanField(default=False),
        ),
    ]
