# Generated by Django 3.2.3 on 2021-06-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_smashnight_automations_ran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rivals',
        ),
        migrations.AddField(
            model_name='person',
            name='rival_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_1_set', to='data.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='rival_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_2_set', to='data.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bracket_demon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demon_set', to='data.person'),
        ),
    ]
