# Generated by Django 3.2.3 on 2021-07-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20210625_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='px_additional_set_wins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='px_set_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchup',
            name='py_additional_set_wins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='py_set_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchup',
            name='set_matchup_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_matchup_set', to='data.matchuptype'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='matchup_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_matchup_set', to='data.matchuptype'),
        ),
    ]
