# Generated by Django 3.2.3 on 2021-07-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_auto_20210708_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mains',
        ),
        migrations.AddField(
            model_name='person',
            name='main_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_1_set', to='data.character'),
        ),
        migrations.AddField(
            model_name='person',
            name='main_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_2_set', to='data.character'),
        ),
        migrations.AddField(
            model_name='person',
            name='main_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_3_set', to='data.character'),
        ),
    ]
