# Generated by Django 3.2.3 on 2022-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20210709_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['sn__date']},
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(0, 'Elite'), (1, 'Challenger'), (3, 'Other')], default=1),
        ),
    ]
