# Generated by Django 3.2.3 on 2023-06-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20220416_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chat_tag',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
