# Generated by Django 4.2.3 on 2023-07-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_person_chat_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name', 'character_id']},
        ),
    ]
