# Generated by Django 4.2.3 on 2023-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_auto_20230709_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='url',
        ),
        migrations.AddField(
            model_name='stage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stages'),
        ),
    ]
