# Generated by Django 4.2.3 on 2023-07-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_venue_venueimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='team/icon'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team/logo'),
        ),
        migrations.AlterField(
            model_name='smashnight',
            name='night_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smashnight',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
