# Generated by Django 4.2.3 on 2023-08-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_migrate_mains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='main_1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='main_2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='main_3',
        ),
    ]
