# Generated by Django 4.2.4 on 2023-08-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_remove_old_mains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rival_1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rival_2',
        ),
    ]
