# Generated by Django 4.2.4 on 2023-08-08 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_greeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='chat_tag',
        ),
    ]
