# Generated by Django 4.2.3 on 2023-09-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_clip_cliptag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliptag',
            name='clip',
        ),
        migrations.AddField(
            model_name='cliptag',
            name='clips',
            field=models.ManyToManyField(related_name='tags', to='data.clip'),
        ),
    ]
