# Generated by Django 4.2.3 on 2023-09-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_remove_cliptag_clip_cliptag_clips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliptag',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
