# Generated by Django 5.0.1 on 2024-01-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_remove_cliptag_clips_clip_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whines', to='data.person')),
            ],
        ),
    ]
