# Generated by Django 5.0.1 on 2024-01-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_whine'),
    ]

    operations = [
        migrations.AddField(
            model_name='whine',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
