# Generated by Django 5.0.1 on 2024-01-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_whine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whine',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
