# Generated by Django 4.2.4 on 2023-09-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_site_alter_sociallink_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='link',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
