# Generated by Django 4.2.3 on 2024-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0070_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='placement_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
