# Generated by Django 5.1.1 on 2024-09-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0071_placement_placement_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='bracket_type',
            field=models.CharField(choices=[('STD', 'STANDARD'), ('RR', 'ROUND_ROBIN')], default='STD', max_length=3),
        ),
    ]
