# Generated by Django 5.1.2 on 2026-03-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_bracket_bracket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=255)),
                ('refresh', models.CharField(max_length=255)),
                ('nickname', models.CharField(default='Unknown User', max_length=40)),
            ],
        ),
    ]
