# Generated by Django 5.2.12 on 2026-03-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_twitchtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tag',
            field=models.IntegerField(blank=True, choices=[(0, 'Member'), (1, 'Guest'), (2, 'Retired'), (3, 'Viewer'), (4, 'Other')], null=True),
        ),
    ]
