# Generated by Django 5.2.12 on 2026-03-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0074_alter_person_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SSBU', max_length=10, unique=True)),
                ('description', models.TextField(null=True, blank=True))
            ],
        ),
    ]
