# Generated by Django 5.2.12 on 2026-03-13 19:22

from django.db import migrations


def create_game_titles(apps, schema_editor):
    GameTitle = apps.get_model("data", "GameTitle")
    title_list = [
        GameTitle(name="SSBU"),
        GameTitle(name="RoA2"),
    ]

    for item in title_list:
        GameTitle.objects.get_or_create(
            name=item.name,
            defaults={
                "name": item.name
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0075_gametitle'),
    ]

    operations = [
        migrations.RunPython(create_game_titles),
    ]
