# Generated by Django 5.2.12 on 2026-03-13 20:02

import data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_auto_20260313_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='game_title',
            field=models.ForeignKey(default=data.models.get_default_game_title, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.gametitle'),
        ),
        migrations.AddField(
            model_name='character',
            name='game_title',
            field=models.ForeignKey(default=data.models.get_default_game_title, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.gametitle'),
        ),
    ]
