# Generated by Django 5.2.12 on 2026-03-13 20:51

from django.db import migrations

def create_initial_characters(apps, schema_editor):
    Character = apps.get_model("data", "Character")
    full_character_list = [
        Character(name='Zetterburn', character_id=83, image_url='https://static.wikitide.net/dragdownwiki/thumb/3/3c/RoA2_Zetterburn_Portrait.png/1024px-RoA2_Zetterburn_Portrait.png'),
        Character(name='Clairen', character_id=84, image_url='https://static.wikitide.net/dragdownwiki/thumb/7/7f/RoA2_Clairen_Portrait.png/1024px-RoA2_Clairen_Portrait.png'),
        Character(name='Loxodont', character_id=85, image_url='https://static.wikitide.net/dragdownwiki/thumb/6/6e/RoA2_Loxodont_Portrait.png/1024px-RoA2_Loxodont_Portrait.png'),
        Character(name='Forsburn', character_id=86, image_url='https://static.wikitide.net/dragdownwiki/thumb/8/86/RoA2_Forsburn_Portrait.png/1024px-RoA2_Forsburn_Portrait.png'),
        Character(name='Kragg', character_id=87, image_url='https://static.wikitide.net/dragdownwiki/thumb/d/d5/RoA2_Kragg_Portrait.png/1024px-RoA2_Kragg_Portrait.png'),
        Character(name='Maypul', character_id=88, image_url='https://static.wikitide.net/dragdownwiki/thumb/d/d7/RoA2_Maypul_Portrait.png/1024px-RoA2_Maypul_Portrait.png'),
        Character(name='Olympia', character_id=89, image_url='https://static.wikitide.net/dragdownwiki/thumb/d/da/RoA2_Olympia_Portrait.png/300px-RoA2_Olympia_Portrait.png'),
        Character(name='Galvan', character_id=90, image_url='https://static.wikitide.net/dragdownwiki/thumb/7/71/RoA2_Galvan_Portrait.png/1024px-RoA2_Galvan_Portrait.png'),
        Character(name='La Reina', character_id=91, image_url='https://static.wikitide.net/dragdownwiki/e/e5/RoA2_La_Reina_Portrait.png'),
        Character(name='Wrastor', character_id=92, image_url='https://static.wikitide.net/dragdownwiki/thumb/a/a0/RoA2_Wrastor_Portrait.png/1024px-RoA2_Wrastor_Portrait.png'),
        Character(name='Fleet', character_id=93, image_url='https://static.wikitide.net/dragdownwiki/thumb/a/ab/RoA2_Fleet_Portrait.png/1024px-RoA2_Fleet_Portrait.png'),
        Character(name='Absa', character_id=94, image_url='https://static.wikitide.net/dragdownwiki/thumb/e/eb/RoA2_Absa_Portrait.png/800px-RoA2_Absa_Portrait.png'),
        Character(name='Ranno', character_id=95, image_url='https://static.wikitide.net/dragdownwiki/thumb/0/02/RoA2_Ranno_Portrait.png/1024px-RoA2_Ranno_Portrait.png'),
        Character(name='Orcane', character_id=96, image_url='https://static.wikitide.net/dragdownwiki/thumb/d/d9/RoA2_Orcane_Portrait.png/1024px-RoA2_Orcane_Portrait.png'),
        Character(name='Etalus', character_id=97, image_url='https://static.wikitide.net/dragdownwiki/thumb/1/18/RoA2_Etalus_Portrait.png/1024px-RoA2_Etalus_Portrait.png'),
    ]
    for item in full_character_list:
        Character.objects.get_or_create(
            name=item.name,
            defaults={
                "character_id": item.character_id,
                "image_url": item.image_url,
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_bracket_game_title_character_game_title'),
    ]

    operations = [
        migrations.RunPython(create_initial_characters),
    ]
