# Generated by Django 5.2.12 on 2026-04-24 23:39

import data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0078_add_rivals_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_title',
            field=models.ForeignKey(default=data.models.get_default_game_title, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.gametitle'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='game_title',
            field=models.ForeignKey(default=data.models.get_default_game_title, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.gametitle'),
        ),
    ]
