# Generated by Django 5.2.12 on 2026-06-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0079_match_game_title_matchup_game_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.UniqueConstraint(fields=('px', 'py', 'game_title'), name='unique_matchup_per_game'),
        ),
    ]
