# Generated by Django 5.2.12 on 2026-06-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_backfill_match_game_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bracket_demon',
        ),
    ]
