# Generated by Django 5.2.16 on 2026-07-16 17:42

import data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_remove_person_bracket_demon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('bronze', models.IntegerField(default=0)),
                ('game_title', models.ForeignKey(default=data.models.get_default_game_title, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.gametitle')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal_set', to='data.person')),
            ],
            options={
                'ordering': ['person', 'game_title'],
                'constraints': [models.UniqueConstraint(fields=('person', 'game_title'), name='unique_medal_per_person_game')],
            },
        ),
    ]
