# Generated by Django 5.2.16 on 2026-07-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0083_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='medal_brackets',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
