# Generated by Django 5.2.16 on 2026-07-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0084_medal_medal_brackets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medal',
            name='bronze',
        ),
        migrations.RemoveField(
            model_name='medal',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='medal',
            name='medal_brackets',
        ),
        migrations.RemoveField(
            model_name='medal',
            name='silver',
        ),
        migrations.AddField(
            model_name='medal',
            name='challenger_bronze',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medal',
            name='challenger_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medal',
            name='challenger_medal_brackets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medal',
            name='challenger_silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medal',
            name='elite_bronze',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medal',
            name='elite_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medal',
            name='elite_medal_brackets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='medal',
            name='elite_silver',
            field=models.IntegerField(default=0),
        ),
    ]
