FROM python:3.11-slim as builder

# Install nginx
RUN \ 
apt update -y && \
apt-get install nginx netcat-traditional -y

COPY nginx.default /etc/nginx/sites-available/default
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
EXPOSE 8020
WORKDIR /sncrs
COPY requirements.txt start_server.sh /sncrs
RUN \ 
pip install --upgrade pip && \
pip install -r requirements.txt --no-cache-dir
COPY . /sncrs
RUN chown -R www-data:www-data /sncrs
STOPSIGNAL SIGTERM
CMD ["/sncrs/start_server.sh"]
